"""Generated contract types from octomil-contracts.

These files are auto-generated by the contract codegen pipeline.
Do not edit manually -- re-run codegen from octomil-contracts instead.
"""

# Span-based telemetry (v1.2.0)
from . import metric_views, span_attributes, span_event_attributes, span_event_names, span_names, span_status_mapping
from .compatibility_level import CompatibilityLevel
from .device_class import DeviceClass
from .error_code import ErrorCode
from .finish_reason import FinishReason
from .model_status import ModelStatus
from .otlp_resource_attributes import (
    OCTOMIL_ACCELERATORS,
    OCTOMIL_AVAILABLE_RUNTIMES,
    OCTOMIL_DEVICE_CLASS,
    OCTOMIL_DEVICE_ID,
    OCTOMIL_ORG_ID,
    OCTOMIL_PLATFORM,
    OCTOMIL_SDK_SURFACE,
    REQUIRED_KEYS,
    SERVICE_NAME,
    SERVICE_VERSION,
    TELEMETRY_SDK_LANGUAGE,
    TELEMETRY_SDK_NAME,
    TELEMETRY_SDK_VERSION,
)
from .telemetry_events import (
    DEPLOY_COMPLETED,
    DEPLOY_STARTED,
    EVENT_REQUIRED_ATTRIBUTES,
    INFERENCE_CHUNK_PRODUCED,
    INFERENCE_COMPLETED,
    INFERENCE_FAILED,
    INFERENCE_STARTED,
)

__all__ = [
    "CompatibilityLevel",
    "DeviceClass",
    "ErrorCode",
    "FinishReason",
    "ModelStatus",
    # OTLP resource attributes
    "SERVICE_NAME",
    "SERVICE_VERSION",
    "TELEMETRY_SDK_NAME",
    "TELEMETRY_SDK_LANGUAGE",
    "TELEMETRY_SDK_VERSION",
    "OCTOMIL_ORG_ID",
    "OCTOMIL_DEVICE_ID",
    "OCTOMIL_PLATFORM",
    "OCTOMIL_SDK_SURFACE",
    "OCTOMIL_DEVICE_CLASS",
    "OCTOMIL_AVAILABLE_RUNTIMES",
    "OCTOMIL_ACCELERATORS",
    "REQUIRED_KEYS",
    # Telemetry events
    "INFERENCE_STARTED",
    "INFERENCE_COMPLETED",
    "INFERENCE_FAILED",
    "INFERENCE_CHUNK_PRODUCED",
    "DEPLOY_STARTED",
    "DEPLOY_COMPLETED",
    "EVENT_REQUIRED_ATTRIBUTES",
    # Span-based telemetry modules
    "span_names",
    "span_attributes",
    "span_event_names",
    "span_event_attributes",
    "span_status_mapping",
    "metric_views",
]
