"""Generated contract types from octomil-contracts.

These files are auto-generated by the contract codegen pipeline.
Do not edit manually -- re-run codegen from octomil-contracts instead.
"""

from .compatibility_level import CompatibilityLevel
from .device_class import DeviceClass
from .error_code import ErrorCode
from .finish_reason import FinishReason
from .model_status import ModelStatus
from .otlp_resource_attributes import (
    OCTOMIL_DEVICE_ID,
    OCTOMIL_ORG_ID,
    OCTOMIL_SDK,
    OS_TYPE,
    REQUIRED_KEYS,
    SERVICE_NAME,
    SERVICE_VERSION,
)
from .telemetry_events import (
    DEPLOY_COMPLETED,
    DEPLOY_STARTED,
    EVENT_REQUIRED_ATTRIBUTES,
    INFERENCE_CHUNK_PRODUCED,
    INFERENCE_COMPLETED,
    INFERENCE_FAILED,
    INFERENCE_STARTED,
)

__all__ = [
    "CompatibilityLevel",
    "DeviceClass",
    "ErrorCode",
    "FinishReason",
    "ModelStatus",
    # OTLP resource attributes
    "SERVICE_NAME",
    "SERVICE_VERSION",
    "OCTOMIL_SDK",
    "OCTOMIL_ORG_ID",
    "OCTOMIL_DEVICE_ID",
    "OS_TYPE",
    "REQUIRED_KEYS",
    # Telemetry events
    "INFERENCE_STARTED",
    "INFERENCE_COMPLETED",
    "INFERENCE_FAILED",
    "INFERENCE_CHUNK_PRODUCED",
    "DEPLOY_STARTED",
    "DEPLOY_COMPLETED",
    "EVENT_REQUIRED_ATTRIBUTES",
]
