"""Generated contract types from octomil-contracts.

These files are auto-generated by the contract codegen pipeline.
Do not edit manually -- re-run codegen from octomil-contracts instead.
"""

# Span-based telemetry (v1.2.0)
from . import (
    metric_views,
    runtime_metric_names,
    span_attributes,
    span_event_attributes,
    span_event_names,
    span_names,
    span_status_mapping,
)
from .artifact_cache_status import ArtifactCacheStatus
from .artifact_resource_kind import ArtifactResourceKind
from .cache_privacy_mode import CachePrivacyMode
from .cache_scope import CacheScope
from .cache_status import CacheStatus
from .compatibility_level import CompatibilityLevel
from .device_class import DeviceClass
from .error_code import ErrorCode
from .execution_mode import ExecutionMode
from .fallback_trigger_stage import FallbackTriggerStage
from .finish_reason import FinishReason
from .modality import Modality
from .model_ref_kind import ModelRefKind
from .model_status import ModelStatus
from .otlp_resource_attributes import (
    OCTOMIL_ACCELERATORS,
    OCTOMIL_AVAILABLE_RUNTIMES,
    OCTOMIL_DEVICE_CLASS,
    OCTOMIL_DEVICE_ID,
    OCTOMIL_INSTALL_ID,
    OCTOMIL_ORG_ID,
    OCTOMIL_PLATFORM,
    OCTOMIL_SDK_SURFACE,
    REQUIRED_KEYS,
    SERVICE_NAME,
    SERVICE_VERSION,
    TELEMETRY_SDK_LANGUAGE,
    TELEMETRY_SDK_NAME,
    TELEMETRY_SDK_VERSION,
)
from .planner_source import PlannerSource
from .route_locality import RouteLocality
from .route_mode import RouteMode
from .runtime_capability import RuntimeCapability

__all__ = [
    "ArtifactResourceKind",
    "ArtifactCacheStatus",
    "CachePrivacyMode",
    "CacheScope",
    "CacheStatus",
    "CompatibilityLevel",
    "DeviceClass",
    "ErrorCode",
    "ExecutionMode",
    "FallbackTriggerStage",
    "FinishReason",
    "Modality",
    "ModelRefKind",
    "ModelStatus",
    "PlannerSource",
    "RouteLocality",
    "RouteMode",
    "RuntimeCapability",
    # OTLP resource attributes
    "SERVICE_NAME",
    "SERVICE_VERSION",
    "TELEMETRY_SDK_NAME",
    "TELEMETRY_SDK_LANGUAGE",
    "TELEMETRY_SDK_VERSION",
    "OCTOMIL_ORG_ID",
    "OCTOMIL_DEVICE_ID",
    "OCTOMIL_INSTALL_ID",
    "OCTOMIL_PLATFORM",
    "OCTOMIL_SDK_SURFACE",
    "OCTOMIL_DEVICE_CLASS",
    "OCTOMIL_AVAILABLE_RUNTIMES",
    "OCTOMIL_ACCELERATORS",
    "REQUIRED_KEYS",
    # Span-based telemetry modules
    "span_names",
    "span_attributes",
    "span_event_names",
    "span_event_attributes",
    "span_status_mapping",
    "metric_views",
    "runtime_metric_names",
]
