"""Auto-generated from octomil-contracts. Do not edit."""

from enum import Enum


class ArtifactStatus(str, Enum):
    NONE = "none"
    """No artifact known or tracked for this slot."""
    DISCOVERED = "discovered"
    """Artifact referenced in desired state but not yet acted upon."""
    DOWNLOADING = "downloading"
    """Artifact download is actively in progress."""
    DOWNLOADED_PARTIAL = "downloaded_partial"
    """Download interrupted; some chunks are on-disk but incomplete."""
    VERIFYING = "verifying"
    """All chunks received; integrity verification (checksum) in progress."""
    VERIFIED = "verified"
    """Artifact passes integrity check and is ready for staging."""
    STAGED = "staged"
    """Artifact is on-disk and ready to be warmed into runtime."""
    WARMING = "warming"
    """Runtime is loading the artifact into memory (pre-activation phase)."""
    ACTIVE = "active"
    """Artifact is loaded and serving inference requests."""
    DRAINING_OLD = "draining_old"
    """Previous version is completing in-flight requests before eviction."""
    FINALIZED = "finalized"
    """Artifact has been replaced by a newer version and is no longer active."""
    GC_ELIGIBLE = "gc_eligible"
    """Artifact is no longer needed and can be evicted from disk by the GC."""
    PAUSED = "paused"
    """Download or activation paused (e.g., waiting for Wi-Fi or charging)."""
    FAILED_RETRYABLE = "failed_retryable"
    """Transient failure during download or staging; eligible for retry."""
    FAILED_CORRUPT = "failed_corrupt"
    """Integrity check failed; artifact data is corrupt and must be re-fetched."""
    FAILED_HEALTHCHECK = "failed_healthcheck"
    """Runtime loaded the artifact but it failed the post-load health check."""
    ROLLBACK_PENDING = "rollback_pending"
    """Activation failed; system is reverting to the previous artifact version."""
    ROLLED_BACK = "rolled_back"
    """Activation failed and device has successfully reverted to the previous artifact version."""
