"""Auto-generated from octomil-contracts. Do not edit."""

from enum import Enum


class ErrorCode(str, Enum):
    NETWORK_UNAVAILABLE = "network_unavailable"
    """No connectivity"""
    REQUEST_TIMEOUT = "request_timeout"
    """Server did not respond in time"""
    SERVER_ERROR = "server_error"
    """5xx from server"""
    INVALID_API_KEY = "invalid_api_key"
    """401 — API key invalid or missing"""
    AUTHENTICATION_FAILED = "authentication_failed"
    """Auth failure (token expired, revoked, malformed)"""
    FORBIDDEN = "forbidden"
    """403 — insufficient permissions"""
    MODEL_NOT_FOUND = "model_not_found"
    """404 — requested model does not exist"""
    MODEL_DISABLED = "model_disabled"
    """Kill switch active for this model"""
    DOWNLOAD_FAILED = "download_failed"
    """Model download error (network, server, storage)"""
    CHECKSUM_MISMATCH = "checksum_mismatch"
    """Integrity check failed after download"""
    INSUFFICIENT_STORAGE = "insufficient_storage"
    """Not enough disk space for model"""
    RUNTIME_UNAVAILABLE = "runtime_unavailable"
    """No compatible runtime for this model format"""
    MODEL_LOAD_FAILED = "model_load_failed"
    """Runtime initialization error"""
    INFERENCE_FAILED = "inference_failed"
    """Prediction error during inference"""
    INSUFFICIENT_MEMORY = "insufficient_memory"
    """OOM during inference or model loading"""
    RATE_LIMITED = "rate_limited"
    """429 — too many requests"""
    INVALID_INPUT = "invalid_input"
    """Bad input data (malformed, wrong type, out of range)"""
    CANCELLED = "cancelled"
    """User or caller cancelled the operation"""
    UNKNOWN = "unknown"
    """Catch-all for unrecognized errors. SDKs MUST map unrecognized codes here."""
