"""Auto-generated from octomil-contracts. Do not edit."""

from enum import Enum


class GateCode(str, Enum):
    ARTIFACT_VERIFIED = "artifact_verified"
    """Artifact integrity verified against expected digest"""
    RUNTIME_AVAILABLE = "runtime_available"
    """Required runtime engine is installed and available"""
    MODEL_LOADS = "model_loads"
    """Model loads successfully into the runtime"""
    CONTEXT_FITS = "context_fits"
    """Request context fits within the model context window"""
    MODALITY_SUPPORTED = "modality_supported"
    """Required modality is supported by the candidate"""
    TOOL_SUPPORT = "tool_support"
    """Required tool calling capability is available"""
    MIN_TOKENS_PER_SECOND = "min_tokens_per_second"
    """Minimum token generation throughput"""
    MAX_TTFT_MS = "max_ttft_ms"
    """Maximum time to first token in milliseconds"""
    MAX_ERROR_RATE = "max_error_rate"
    """Maximum historical error rate within a window"""
    MIN_FREE_MEMORY_BYTES = "min_free_memory_bytes"
    """Minimum free memory required for model execution"""
    MIN_FREE_STORAGE_BYTES = "min_free_storage_bytes"
    """Minimum free storage required for artifact"""
    BENCHMARK_FRESH = "benchmark_fresh"
    """Benchmark data is within the required freshness window"""
    MIN_BATTERY_PCT = "min_battery_pct"
    """Minimum battery percentage required for local inference"""
    MAX_THERMAL_STATE = "max_thermal_state"
    """Maximum thermal state for local inference (nominal < fair < serious < critical)"""
    REQUIRE_CHARGING = "require_charging"
    """Device must be charging/plugged in for local inference"""
    REQUIRE_WIFI = "require_wifi"
    """WiFi connection required for artifact download or preparation"""
    SCHEMA_VALID = "schema_valid"
    """Output conforms to a provided JSON schema"""
    TOOL_CALL_VALID = "tool_call_valid"
    """Tool call names and arguments match declared tool definitions"""
    SAFETY_PASSED = "safety_passed"
    """Output passes configured safety evaluation"""
    EVALUATOR_SCORE_MIN = "evaluator_score_min"
    """App-owned evaluator returned a score meeting the minimum threshold"""
    JSON_PARSEABLE = "json_parseable"
    """Output is valid parseable JSON"""
    MAX_REFUSAL_RATE = "max_refusal_rate"
    """Historical refusal rate is within acceptable bounds"""
