"""Auto-generated from octomil-contracts. Do not edit."""

from enum import Enum


class RuntimeExecutor(str, Enum):
    COREML = "coreml"
    """Apple Core ML runtime"""
    MLX = "mlx"
    """Apple MLX framework"""
    LITERT = "litert"
    """Google LiteRT (formerly TensorFlow Lite)"""
    ONNXRUNTIME = "onnxruntime"
    """Microsoft ONNX Runtime"""
    LLAMACPP = "llamacpp"
    """llama.cpp inference engine"""
    MNN = "mnn"
    """Alibaba MNN runtime"""
    TRANSFORMERSJS = "transformersjs"
    """Hugging Face Transformers.js (WASM + WebGPU)"""
    CLOUD = "cloud"
    """Server-side cloud inference (not on-device)"""
    OLLAMA = "ollama"
    """Ollama local inference server"""
    WHISPER = "whisper"
    """Whisper.cpp audio transcription engine"""
    MLC = "mlc"
    """MLC-LLM compiled inference engine"""
    CACTUS = "cactus"
    """Cactus cross-platform inference engine"""
    SAMSUNG_ONE = "samsung_one"
    """Samsung ONE (On-device Neural Engine) runtime"""
    EXECUTORCH = "executorch"
    """Meta ExecuTorch runtime"""
    ECHO = "echo"
    """Stub engine for testing only. Never shipped."""
