"""Routing layer: candidate attempt runner and route event telemetry."""

from octomil.runtime.routing.attempt_runner import (
    GATE_CLASSIFICATION,
    ArtifactChecker,
    AttemptArtifact,
    AttemptLoopResult,
    AttemptStage,
    AttemptStatus,
    CandidateAttemptRunner,
    FallbackTrigger,
    GateEvaluator,
    GateResult,
    GateStatus,
    OutputQualityGateEvaluator,
    RouteAttempt,
    RuntimeChecker,
    classify_gate,
)
from octomil.runtime.routing.evaluators import (
    EvaluatorRegistry,
    EvaluatorResult,
    JsonParseableEvaluator,
    JsonSchemaEvaluator,
    OutputQualityEvaluator,
    RegexPredicateEvaluator,
    RegistryBackedEvaluator,
    SafetyPassedEvaluator,
    ToolCallValidEvaluator,
)
from octomil.runtime.routing.model_ref import (
    CANONICAL_MODEL_REF_KINDS,
    ParsedModelRef,
    parse_model_ref,
)
from octomil.runtime.routing.route_event import (
    FORBIDDEN_TELEMETRY_KEYS,
    CandidateAttemptSummary,
    RouteEvent,
    build_route_event,
    emit_route_event,
    strip_forbidden_keys,
)

__all__ = [
    "ArtifactChecker",
    "AttemptArtifact",
    "AttemptLoopResult",
    "AttemptStage",
    "AttemptStatus",
    "CandidateAttemptRunner",
    "FallbackTrigger",
    "FORBIDDEN_TELEMETRY_KEYS",
    "GATE_CLASSIFICATION",
    "CANONICAL_MODEL_REF_KINDS",
    "GateEvaluator",
    "GateResult",
    "GateStatus",
    "OutputQualityEvaluator",
    "OutputQualityGateEvaluator",
    "EvaluatorResult",
    "EvaluatorRegistry",
    "RegistryBackedEvaluator",
    "JsonParseableEvaluator",
    "JsonSchemaEvaluator",
    "ToolCallValidEvaluator",
    "RegexPredicateEvaluator",
    "SafetyPassedEvaluator",
    "CandidateAttemptSummary",
    "RouteAttempt",
    "RouteEvent",
    "RuntimeChecker",
    "ParsedModelRef",
    "build_route_event",
    "classify_gate",
    "emit_route_event",
    "parse_model_ref",
    "strip_forbidden_keys",
]
